version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    reqwest:
      patterns:
      - "reqwest*"
- package-ecosystem: docker
  directories:
    - "*"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
