---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1
  disable: true

environment:
  CARGO_HTTP_CAINFO: /drone/src/certs/sys/proxy_deps_ca.pem
  CURL_CA_BUNDLE: /drone/src/certs/sys/proxy_deps_ca.pem
  GIT_SSL_CAINFO: /drone/src/certs/sys/proxy_deps_ca.pem
  HEX_CACERTS_PATH: /drone/src/certs/sys/proxy_deps_ca.pem
  NODE_EXTRA_CA_CERTS: /drone/src/certs/sys/proxy_deps_ca.pem
  REQUESTS_CA_BUNDLE: /drone/src/certs/sys/proxy_deps_ca.pem
  SYSTEM_CERTIFICATE_PATH: /drone/src/certs/sys/proxy_deps_ca.pem
  http_proxy: http://mitmproxy.servicediscovery.prima:8080
  https_proxy: http://mitmproxy.servicediscovery.prima:8080
  no_proxy: localhost,redis,rabbit,aws,statsd,postgres,mysql,web,e2e-backend,127.0.0.1,elasticsearch,db,kibana,mock
steps:
- name: clone
  image: drone/git
  environment:
    CARGO_HTTP_CAINFO: ""
    CURL_CA_BUNDLE: ""
    GIT_SSL_CAINFO: ""
    HEX_CACERTS_PATH: ""
    NODE_EXTRA_CA_CERTS: ""
    REQUESTS_CA_BUNDLE: ""
    SYSTEM_CERTIFICATE_PATH: ""
    http_proxy: ""
    https_proxy: ""

- name: pre-start
  image: prima/drone-tools:1.17.8
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - pre-start-scripts
  environment:
    CARGO_HTTP_CAINFO: ""
    CURL_CA_BUNDLE: ""
    GIT_SSL_CAINFO: ""
    HEX_CACERTS_PATH: ""
    NODE_EXTRA_CA_CERTS: ""
    REQUESTS_CA_BUNDLE: ""
    SYSTEM_CERTIFICATE_PATH: ""
    http_proxy: ""
    https_proxy: ""
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint

- name: cache-restore
  image: prima/drone-tools:1.17.8
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    CARGO_HTTP_CAINFO: ""
    CURL_CA_BUNDLE: ""
    GIT_SSL_CAINFO: ""
    HEX_CACERTS_PATH: ""
    NODE_EXTRA_CA_CERTS: ""
    REQUESTS_CA_BUNDLE: ""
    SYSTEM_CERTIFICATE_PATH: ""
    http_proxy: ""
    https_proxy: ""
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock

- name: check-secrets
  image: prima/drone-tools:1.17.8
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - check-secrets-grants
  environment:
    CARGO_HTTP_CAINFO: ""
    CURL_CA_BUNDLE: ""
    GIT_SSL_CAINFO: ""
    HEX_CACERTS_PATH: ""
    NODE_EXTRA_CA_CERTS: ""
    REQUESTS_CA_BUNDLE: ""
    SYSTEM_CERTIFICATE_PATH: ""
    http_proxy: ""
    https_proxy: ""
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint

- name: build-image
  image: prima/drone-tools:1.17.8
  commands:
  - sed -i 's/USER app/USER root/g' ./Dockerfile
  - docker build -t prima/bridge.rs-ci:1 ./
  environment:
    CARGO_HTTP_CAINFO: ""
    CURL_CA_BUNDLE: ""
    GIT_SSL_CAINFO: ""
    HEX_CACERTS_PATH: ""
    NODE_EXTRA_CA_CERTS: ""
    REQUESTS_CA_BUNDLE: ""
    SYSTEM_CERTIFICATE_PATH: ""
    http_proxy: ""
    https_proxy: ""
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - cache-restore
  - clone

- name: cargo-format
  image: prima/bridge.rs-ci:1
  commands:
  - cargo make --profile drone format-ci
  environment:
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - build-image
  - pre-start

- name: cargo-lint
  image: prima/bridge.rs-ci:1
  commands:
  - cargo make --profile drone clippy-ci
  environment:
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - cargo-format

- name: cargo-test
  image: prima/bridge.rs-ci:1
  commands:
  - cargo make --profile drone test
  environment:
    CARGO_HOME: /drone/src/.cargo
    CARGO_HTTP_CAINFO: ""
    http_proxy: ""
    https_proxy: ""
  depends_on:
  - cargo-lint

- name: cargo-build
  image: prima/bridge.rs-ci:1
  commands:
  - cargo make --profile drone build-ci
  environment:
    CARGO_HOME: /drone/src/.cargo
  when:
    branch:
      exclude:
      - master
  depends_on:
  - cargo-test

- name: cache-cleanup
  image: prima/bridge.rs-ci:1
  commands:
  - cargo make --profile drone cache-cleanup
  when:
    branch:
    - master
  depends_on:
  - cargo-build
  - cargo-format
  - cargo-lint
  - cargo-test

- name: cache-save
  image: prima/drone-tools:1.17.8
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-save .cargo target
  environment:
    CARGO_HTTP_CAINFO: ""
    CURL_CA_BUNDLE: ""
    GIT_SSL_CAINFO: ""
    HEX_CACERTS_PATH: ""
    NODE_EXTRA_CA_CERTS: ""
    REQUESTS_CA_BUNDLE: ""
    SYSTEM_CERTIFICATE_PATH: ""
    http_proxy: ""
    https_proxy: ""
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master
  depends_on:
  - cache-cleanup

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint

trigger:
  event:
  - push

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: drillster/drone-email
  settings:
    from: noreply@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  event:
  - push
  status:
  - failure

depends_on:
- default

---
kind: signature
hmac: 99e9322c10fe27e9865f432008ac09ae997d68782cb683eb6ac5518fd85ca443

...
