version: "3"
services:
  bridge:
    build:
      context: .
    environment:
      BUILD_ENV: dev
      CARGO_HOME: /home/app/.cargo
      CARGO_TARGET_DIR: /home/app/target
      CARGO_MAKE_DISABLE_UPDATE_CHECK: 1
    volumes:
      - ".:/code"
      - "app:/home/app/"
      - "~/.aws:/home/app/.aws"
      - "~/.ssh:/home/app/.ssh"
      - "~/.gitconfig:/home/app/.gitconfig"
      - "~/.gitignore:/home/app/.gitignore"
    tty: true
    stdin_open: true

volumes:
  app:
