[config]
skip_core_tasks = true

[tasks.build]
description = "Runs the rust compiler."
category = "Build"
install_crate = false
command = "cargo"
args = [
    "build",
    "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
    "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]

[tasks.fmt-check]
description = "Runs the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.test]
dependencies = [
    "test-base",
    "test-auth0",
    "test-otel-0_20",
    "test-otel-0_21",
    "test-otel-0_22",
    "test-otel-0_23"
]

[tasks.test-base]
command = "cargo"
args = ["test", "--features", "gzip", "${@}"]
dependencies = ["build"]

[tasks.test-otel-0_20]
command = "cargo"
args = ["test", "--no-default-features", "--features", "tracing_opentelemetry_0_20"]

[tasks.test-otel-0_21]
command = "cargo"
args = ["test", "--no-default-features", "--features", "tracing_opentelemetry_0_21"]

[tasks.test-otel-0_22]
command = "cargo"
args = ["test", "--no-default-features", "--features", "tracing_opentelemetry_0_22"]

[tasks.test-otel-0_23]
command = "cargo"
args = ["test", "--no-default-features", "--features", "tracing_opentelemetry_0_23"]

[tasks.test-auth0]
command = "cargo"
args = ["test", "--features=auth0,gzip", "${@}"]
dependencies = ["build"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--", "-D", "warnings"]

[tasks.deny-check]
dependencies = [
    "deny-check-otel-0_20",
    "deny-check-otel-0_21",
    "deny-check-otel-0_22",
    "deny-check-otel-0_23"
]

[tasks.deny-check-otel-0_20]
args = ["deny", "--no-default-features", "--features", "tracing_opentelemetry_0_20", "check"]
command = "cargo"
description = "Run cargo-deny with tracing_opentelemetry_0_20 feature"

[tasks.deny-check-otel-0_21]
args = ["deny", "--no-default-features", "--features", "tracing_opentelemetry_0_21", "check"]
command = "cargo"
description = "Run cargo-deny with tracing_opentelemetry_0_21 feature"

[tasks.deny-check-otel-0_22]
args = ["deny", "--no-default-features", "--features", "tracing_opentelemetry_0_22", "check"]
command = "cargo"
description = "Run cargo-deny with tracing_opentelemetry_0_22 feature"

[tasks.deny-check-otel-0_23]
args = ["deny", "--no-default-features", "--features", "tracing_opentelemetry_0_23", "check"]
command = "cargo"
description = "Run cargo-deny with tracing_opentelemetry_0_23 feature"

[tasks.docs]
description = "Build docs as they are rendered on docs.rs"
command = "cargo"
args = ["doc", "--document-private-items", "--all-features", "--no-deps"]
env = { "RUSTDOCFLAGS" = "-Dwarnings" }

[tasks.release]
description = "Task to release the package to crates.io"
command = "cargo"
args = ["publish", "--no-verify"]
