name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup default 1.91.0
      - run: rustup component add clippy rustfmt
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # ratchet:Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2.85.11
        with:
          tool: cargo-make,cargo-deny@0.19
      - run: cargo make fmt-check
      - run: cargo make clippy
      - run: cargo make deny-check
      - run: cargo make docs
  test:
    services:
      aws:
        image: motoserver/moto:5.1.21
        env:
          # Set up moto in a way that matches localstack
          MOTO_PORT: 4566
          MOTO_ACCOUNT_ID: "000000000000"
        ports:
          - "4566:4566"
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_REGION: eu-west-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup default 1.91.0
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # ratchet:Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # 2.85.11
        with:
          tool: cargo-make
      - run: cargo make test

  alls-green:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - run: ${{ !contains(needs.*.result, 'failure') }}
